# Generated by Django 2.2 on 2022-09-30 07:10

import builtins
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20220930_1228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categ',
            options={'ordering': [builtins.id], 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
